In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'customer_id': [1, 2, 3, 4, 2, 5],
    'age':         [25, np.nan, 35, np.nan, np.nan, 40],
    'city':        ['Mumbai', 'Delhi', np.nan, 'Mumbai', 'Delhi', np.nan],
    'gender':      ['Male', 'Female', 'Female', 'Male', 'Female', 'Male'],
    'annual_income': [40000, 80000, 60000, 120000, 80000, 95000]
})

TASK-**1**

In [2]:
df.isnull().sum()

customer_id      0
age              3
city             2
gender           0
annual_income    0
dtype: int64

In [8]:
df['age']=df['age'].fillna(df['age'].median())

In [24]:
df['city']=df['city'].fillna(df['city'].mode()[0])

In [23]:
df

   customer_id        age    city  gender  annual_income
0            1  25.000000  Mumbai    Male          40000
1            2  33.333333   Delhi  Female          80000
2            3  35.000000   Delhi  Female          60000
3            4  33.333333  Mumbai    Male         120000
4            2  33.333333   Delhi  Female          80000
5            5  40.000000   Delhi    Male          95000

In [13]:
df.isnull().sum()

customer_id      0
age              0
city             0
gender           0
annual_income    0
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(1)

In [29]:
df=df.drop_duplicates()

In [30]:
df.duplicated().sum()

np.int64(0)

TASK-**2**

In [39]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['gender']=le.fit_transform(df[['gender']])

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [43]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

en = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

city_encoded_array = en.fit_transform(df[['city']])

feature_names = en.get_feature_names_out(['city'])

df_city_encoded = pd.DataFrame(city_encoded_array, columns=feature_names, index=df.index)

# Drop the original 'city' column and concatenate the new encoded columns
df = pd.concat([df.drop('city', axis=1), df_city_encoded], axis=1)

In [44]:
df

   customer_id       age  gender  annual_income  city_Delhi  city_Mumbai
0            1  0.000000       1         0.0000         0.0          1.0
1            2  0.555556       0         0.5000         1.0          0.0
2            3  0.666667       0         0.2500         1.0          0.0
3            4  0.555556       1         1.0000         0.0          1.0
5            5  1.000000       1         0.6875         1.0          0.0

TASK-**3**

In [33]:
#Scaling
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
df['annual_income']=scaler.fit_transform(df[['annual_income']])
df['age']=scaler.fit_transform(df[['age']])

In [34]:
df

   customer_id       age    city  gender  annual_income
0            1 -1.725164  Mumbai    Male      -1.410970
1            2  0.000000   Delhi  Female       0.036179
2            3  0.345033   Delhi  Female      -0.687396
3            4  0.000000  Mumbai    Male       1.483328
5            5  1.380131   Delhi    Male       0.578860

In [36]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
df['annual_income']=scaler.fit_transform(df[['annual_income']])
df['age']=scaler.fit_transform(df[['age']])

In [40]:
df

   customer_id       age    city  gender  annual_income
0            1  0.000000  Mumbai       1         0.0000
1            2  0.555556   Delhi       0         0.5000
2            3  0.666667   Delhi       0         0.2500
3            4  0.555556  Mumbai       1         1.0000
5            5  1.000000   Delhi       1         0.6875